### ISSUE TITLE
项目中怎么用的？能否给个例子呢？

### ISSUE THREAD

**Issue by chaim007** [moonou/wepy-plugin-iconfont#1]
帮忙在readme里面加个项目使用的例子哈。。。

**Comment by moonou** [comment]
不好意思，才看到issue。

该插件是在wepy1.x时期开发的，现在wepy已经升级到2.x了，wepy2目前的插件机制有所改动，所以插件的代码需要调整。我最近会寻找方案将这个插件升级支持wepy2。

如果你是使用1.x版本的wepy，按照现有[README](https://github.com/moonou/wepy-plugin-iconfont/blob/master/README.md)配置好后，在模板里面使用`<i class="iconfont icon-down"></i>`类似的语法就可以使用了，其中`icon-down`是你iconfont里面定义的class名称。

**Comment by moonou** [comment]
README已经更新
